### ISSUE TITLE
Fabric loader crash fix and additional mods link

### ISSUE THREAD

**Issue by wiredestroyer** [VoidAndCaffeine/Block_Breaking_SMP_mods#2]
https://lambdaurora.dev/optifine_alternatives/

If you need it ^

Update fabric loader from 1.12.11 to 1.12.12 by creating a new profile 

P.s. Thanks Void, this is extremely convenient!

**Comment by VoidAndCaffeine** [comment]
gonna check out lamb and the other things on the list :)

added fabric 1.12.12 to the pre-recs 

closing the issue :)
